create table if not exists public.source_channels (
    id bigint generated by default as identity primary key,
    username text not null check (length(btrim(username)) > 0),
    display_name text,
    source_chat_id bigint unique,
    enabled boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists source_channels_username_normalized_key
on public.source_channels (lower(trim(leading '@' from btrim(username))));

create table if not exists public.important_keywords (
    id bigint generated by default as identity primary key,
    phrase text not null check (length(btrim(phrase)) > 0),
    language text,
    category text,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists important_keywords_phrase_normalized_key
on public.important_keywords (lower(btrim(phrase)));

create table if not exists public.app_settings (
    id smallint primary key default 1 check (id = 1),
    destination text not null,
    important_destination text,
    backfill_days integer not null default 2 check (backfill_days >= 0),
    config_refresh_seconds integer not null default 60
        check (config_refresh_seconds >= 10),
    updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists source_channels_updated_at on public.source_channels;
create trigger source_channels_updated_at
before update on public.source_channels
for each row execute function public.set_updated_at();

drop trigger if exists important_keywords_updated_at on public.important_keywords;
create trigger important_keywords_updated_at
before update on public.important_keywords
for each row execute function public.set_updated_at();

drop trigger if exists app_settings_updated_at on public.app_settings;
create trigger app_settings_updated_at
before update on public.app_settings
for each row execute function public.set_updated_at();

alter table public.source_channels enable row level security;
alter table public.important_keywords enable row level security;
alter table public.app_settings enable row level security;

revoke all on public.source_channels from anon, authenticated;
revoke all on public.important_keywords from anon, authenticated;
revoke all on public.app_settings from anon, authenticated;

grant select, insert, update, delete on public.source_channels to service_role;
grant select, insert, update, delete on public.important_keywords to service_role;
grant select, insert, update on public.app_settings to service_role;
grant usage, select on sequence public.source_channels_id_seq to service_role;
grant usage, select on sequence public.important_keywords_id_seq to service_role;

insert into public.source_channels
    (username, source_chat_id, enabled, sort_order)
values
    ('PalpostN', -1001026262375, true, 10),
    ('walaatdiscu', -1001289119515, true, 20),
    ('Ramallah_ii', -1002417348271, true, 30),
    ('raskarkarpal2', -1001578919049, true, 40),
    ('almzraa20233', -1001819254886, true, 50),
    ('raskarkarpal', -1001570562265, true, 60),
    ('bitllo_news1', -1002805118080, true, 70),
    ('aljania1', -1002635927257, true, 80)
on conflict do nothing;

insert into public.important_keywords (phrase, enabled)
values
    ('اغتيال', true),
    ('صاروخ', true),
    ('إطلاق نار', true),
    ('חדירה', true),
    ('פיגוע', true),
    ('חטיפה', true),
    ('נריה', true),
    ('דולב', true),
    ('טלמון', true),
    ('נחליאל', true),
    ('נעלה', true),
    ('שדה אפריים', true),
    ('עין איוב', true),
    ('צומת הדואר', true),
    ('ראס כרכר', true),
    ('חרבתא', true),
    ('ביתילו', true),
    ('דיר עמאר', true),
    ('دير عمار', true),
    ('بتيللو', true),
    ('راس كركر', true),
    ('عين عريك', true),
    ('عين قينيا', true),
    ('خربثا بني حارث', true),
    ('ביטיללו', true),
    ('ראס קרקר', true),
    ('עין אריק', true),
    ('עין קיניה', true),
    ('חרבתא בני חרית''', true),
    ('الجانية', true),
    ('ג''ניה', true),
    ('المزرعة القبلية', true),
    ('אלמזרע אלקבליה', true),
    ('المزرعة اغربية', true),
    ('جبل الريسان', true),
    ('שדה אפרים', true),
    ('نبي عنير', true),
    ('נבי ענר', true)
on conflict do nothing;

insert into public.app_settings
    (id, destination, important_destination, backfill_days, config_refresh_seconds)
values
    (1, 'ערבית מתורגם', 'ערבית מתורגם-חשוב', 2, 60)
on conflict (id) do nothing;
